name: Create GCP infrastructure

on:
  workflow_dispatch:
    inputs:
      project:
        default: study-326317
        required: true
        description: 'Cloud Project'
      environment:
        default: 'development'
        required: true
        description: 'Environment'

jobs:
  create-infrastructure:
    name: Create infrastructure
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authorize GCP
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_KEY }}
        project_id: ${{ github.event.inputs.project }}

    - name: Terraform setup
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_KEY }}
      run: |-
        cd src
        terraform init

    - name: Terraform apply
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_KEY }}
      run: |-
        cd src
        terraform apply -var="project_id=${{ github.event.inputs.project }}" -var-file=../src/${{ github.event.inputs.environment }}/env.tfvars -auto-approve