name: Create GCP infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        default: 'development'
        required: true
        description: 'Environment'

jobs:
  create-infrastructure:
    name: Create infrastructure
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authorize GCP
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Terraform setup
      uses: hashicorp/setup-terraform@v1

    - name: Terraform init
      run: terraform init

    - name: Terraform apply
      run: terraform apply -var="project_id=${{ secrets.GCP_PROJECT }}" -var-file=../src/${{ github.event.inputs.environment }}"/env.tfvars -auto-approve