name: Create GCP infrastructure

on:
  workflow_dispatch:
    inputs:
      region:
        default: 'northamerica-northeast1'
        required: true
        description: 'Cloud Region'
      zone:
        default: 'northamerica-northeast1-c'
        required: true
        description: 'Cloud Zone'
      environment:
        default: 'development'
        required: true
        description: 'Environment'

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - run: |-
        make create ENVIRONMENT=${{ github.event.inputs.environment }}